# Generated by Django 5.0.7 on 2024-10-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name', max_length=100)),
                ('contact_no', models.CharField(help_text='Your contact number', max_length=100)),
                ('email', models.EmailField(help_text='Your email address', max_length=254)),
                ('description', models.TextField(help_text='A short description about you')),
                ('image', models.ImageField(help_text='Your avatar', upload_to='about')),
                ('available', models.BooleanField(default=True)),
                ('experience', models.IntegerField(help_text='Your experience')),
                ('projects_completed', models.IntegerField(help_text='Number of projects completed')),
                ('happy_clients', models.IntegerField(help_text='Number of happy clients')),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarding_organization', models.CharField(help_text='Name of the awarding organization', max_length=100)),
                ('year', models.IntegerField(help_text='Year of the award')),
                ('position', models.CharField(help_text='Position achieved', max_length=100)),
                ('project_link', models.URLField(help_text='Link to the project')),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(help_text='Brands You have collaborated with [png]', upload_to='brands')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='Reviewers role i.e. CEO, CTO', max_length=100)),
                ('description', models.CharField(help_text='Your review', max_length=500)),
                ('rating', models.IntegerField(help_text='Rating out of 5')),
            ],
        ),
    ]
