# Generated by Django 5.0.7 on 2024-10-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='awards',
            options={'verbose_name': 'Award', 'verbose_name_plural': 'Awards'},
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='about',
            name='fb_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='github_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='pintrest_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
