# Generated by Django 5.0.7 on 2024-10-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_awards_name_alter_brands_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='icon',
            field=models.ImageField(default=1, help_text='Icon of the award', upload_to='awards'),
            preserve_default=False,
        ),
    ]
