# Generated by Django 5.0.7 on 2024-10-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_awards_awarding_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_icon', models.ImageField(help_text='Icon of the skill 50x50 [png]', upload_to='expertise')),
            ],
            options={
                'verbose_name': 'Expertise',
                'verbose_name_plural': 'Expertise',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
                ('organization_image', models.ImageField(help_text='Logo of the organization 50x50 [png]', upload_to='experience')),
                ('designation', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_year', models.IntegerField(help_text='Year of start')),
                ('end_year', models.IntegerField(help_text='Year of end')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experience',
            },
        ),
        migrations.AlterField(
            model_name='awards',
            name='icon',
            field=models.ImageField(help_text='Icon of the award 50x50 [png] !important', upload_to='awards'),
        ),
    ]
