# Generated by Django 5.0.7 on 2024-10-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_expertise_workexperience_alter_awards_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='description',
        ),
    ]
