# Generated by Django 5.0.7 on 2024-10-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_projects_client_name_projects_over_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='over_view',
            field=models.CharField(max_length=700),
        ),
    ]
